### ISSUE TITLE
Conformance report for reference

### ISSUE THREAD

**Issue by miloyip** [chadaustin/sajson#14]
https://github.com/miloyip/nativejson-benchmark/blob/master/sample/conformance_sajson%20(C%2B%2B).md

**Comment by chadaustin** [comment]
Thanks @miloyip for the bug reports!  Your validation suite is excellent.

I fixed some of the issues:

https://github.com/chadaustin/sajson/commit/a1a4b8db9fb363fbf0c7ef12a7d2d0c0fc1ee448
https://github.com/chadaustin/sajson/commit/9992758580311723162f9dfbdeb19373e1e95f62
https://github.com/chadaustin/sajson/commit/4272e4d1b67f8f8b40acb5bcc8524f1f4470422a
https://github.com/chadaustin/sajson/commit/9c79e8874cb9efbd15b8866adc6bcb1cd9f1648d

The double precision edge cases are a won't-fix because the JSON RFC says implementations are allowed to have unspecified precision, and sajson was built to quickly parse "normalized" numeric values.

Thanks again!

**Comment by chadaustin** [comment]
Oh, and p.s., I tried to build the json validation suite on my Ubuntu 16.04 laptop but getting premake5 was proving to be challenging so I gave up.  If you see that the latest sajson regresses in any way, please let me know!
