### ISSUE TITLE
Parsing big integers

### ISSUE THREAD

**Issue by ksergey** [chadaustin/sajson#25]
Hi,

sajson interpret big numbers like 1496756396000 as double, because
```
                if (SAJSON_UNLIKELY(!try_double && i > INT_MAX / 10 - 9)) {                                                                        
                    // TODO: could split this into two loops                                                                                       
                    try_double = true;                                                                                                             
                    d = i;                                                                                                                                         
                } 
```

Could you please fix that?

**Comment by chadaustin** [comment]
Hi @ksergey,

Just to clarify - what would you expect to happen here?  That number is too big to fit into a 32-bit integer but does fit exactly in the double (as it's under 53 bits).

Can you explain a little bit about your use case?

Thanks!
Chad

**Comment by ksergey** [comment]
Hi @chadaustin 

I try to use your library for pasing data from Bitfinex exchange. The exchange send timestamps as microseconds since Epoch. 

1. Converting to double integer types looks like a hack. Example:
```
expected message format: [ <TYPE_INT>,  <TYPE_STRING> ]
msg 1: [ 5, "hello" ]
msg 2: [ 1496756396000, "world" ]
```
In this case I should check get_type() == TYPE_INT || get_type() = TYPE_DOUBLE. What if first element will be real DOUBLE? I can't detect this case in my application.

2. For value 1496756396000 get_double_value() returns -2147483648 (std::cout)

Thanks

**Comment by chadaustin** [comment]
@ksergey Sorry for the slow response (been quite busy)

To give a bit of background here, the JSON spec doesn't specify any required precision of numbers.  But since JSON originated in JavaScript, which only has a single numeric type (double-precision floats) the situation is a bit murky.  In practice, few people actually store 64-bit integers in JSON, because otherwise JavaScript wouldn't be able to read them.  However, you can represent 53-bit integers in a double!  So usually people end up only using JSON numbers for integers 53 bits or smaller, and otherwise encode large integers in strings.  I think that's what you're seeing here.  Microseconds since epoch fits in 52 bits until the next century.

What would you think if I added an sajson API something like `get_int53_value()` that returned an `int64_t`?

**Comment by chadaustin** [comment]
I'm a little bit confused about the `get_double_value` behavior you reported.  This test passes in the sajson test suite:

```
    ABSTRACT_TEST(large_number) {
        const auto& document = parse(literal("[1496756396000]"));
        assert(success(document));
        const value& root = document.get_root();
        CHECK_EQUAL(TYPE_ARRAY, root.get_type());
        CHECK_EQUAL(1u, root.get_length());

        const value& element = root.get_array_element(0);
        CHECK_EQUAL(TYPE_DOUBLE, element.get_type());
        CHECK_EQUAL(1496756396000.0, element.get_double_value());
    }
```

**Comment by ksergey** [comment]
@chadaustin thank you, I resolved the issue on my side

**Comment by chadaustin** [comment]
FYI, I did add get_int53_value in https://github.com/chadaustin/sajson/commit/d8efea469a36e85bcb24ba973c8f44280e6384ea

Hopefully it makes your life a bit more convenient!
